FMS.MVC/Controllers/CommentsController.cs
using FMS.Data.Models;
using FMS.Data.Utilities.Exceptions;
using FMS.Services.DTOs;
using FMS.Services.Mappers;
using FMS.Services.Services.Contracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;

namespace FMS.MVC.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentsService commentsService;
        private readonly IPostsService postsService;
        private readonly IAuthManager authManager;

        public CommentsController(
            ICommentsService commentsService,
            IPostsService postsService,
            IAuthManager authManager)
        {
            this.commentsService = commentsService;
            this.postsService = postsService;
            this.authManager = authManager;
        }
        // GET: CommentsController
        public ActionResult Index()
        {
            return View();
        }

        // GET: CommentsController/Details/5
        public ActionResult Details(CommentResponseDTO responce)
        {
            return View(responce);
        }

        [HttpGet]
        // GET: CommentsController/Create
        public ActionResult Create(int postId)
        {
            var model = new CommentInputDTO { PostId = postId };
            return View(model);
        }

        // POST: CommentsController/Create
        [HttpPost]
        public ActionResult Create(int postId, CommentInputDTO model)
        {
            model.PostId = postId;

            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var post = this.postsService.GetById(model.PostId);
                var user = this.authManager.CurrentUser;
                var createdComment = this.commentsService.Create(model.MapToCommentModel(user, post));
                var responce = createdComment.MapToCommentResponse();
                return View("Details", responce);
            }
            catch (ApplicationException)
            {
                return this.RedirectToAction(actionName: "Index", controllerName: "Home");
            }
            catch (Exception)
            {
                return this.Redirect("/Shared/Error");
            }
        }

        [HttpGet]
        // GET: CommentsController/Edit/5
        public ActionResult Edit(int commentId)
        {
            var currentContent = this.commentsService.GetById(commentId).Content;
            var model = new CommentInputDTO { CommentId = commentId, Content = currentContent };
            return View(model);
        }

        // POST: CommentsController/Edit/5
        [HttpPost]
        public ActionResult Edit(int commentId, CommentInputDTO model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            try
            {
                this.commentsService.Update(commentId, model.Content);
                return this.RedirectToAction(actionName: "Index", controllerName: "Home");
            }
            catch (ApplicationException)
            {
                return this.RedirectToAction(actionName: "Index", controllerName: "Home");
            }
            catch (Exception)
            {
                return this.Redirect("/Error");
            }
        }

        [HttpGet]
        // GET: CommentsController/Delete/5
        public ActionResult Delete(int commentId)
        {
            var model = this.commentsService.GetById(commentId);
            return View(model);
        }

        // POST: CommentsController/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int commentId)
        {
            try
            {
                this.commentsService.Delete(this.commentsService.GetById(commentId));
                return this.RedirectToAction(actionName: "Index", controllerName: "Home");
            }
            catch (ApplicationException) 
            {
                return this.RedirectToAction(actionName: "Index", controllerName: "Home");

            }
            catch (Exception)
            {
                return this.Redirect("/Error");
            }
        }
    }
}

FMS.MVC/Views/Comments/Create.cshtml
@model CommentInputDTO
@inject IPostsService posetsService
@inject IAuthManager authManager

@{
    var post = this.posetsService.GetById(this.Model.PostId);
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h2>
                You are writing a comment for: <a asp-controller="Posts" asp-action="Details" asp-route-postId="@this.Model.PostId">@post.Title</a>
            </h2>
        </div>
        <div class="panel-body">
            <div class="media pull-left">
                <div class="pull-left">
                    <a href="#">
                        <img class="media-object img-circle img-comments" src="~/assets/img/user.gif" />
                    </a>
                    <p class="text-info d-inline pull-right"><a>User details</a></p>
                    <p>@post.CreatedOn.ToShortDateString()</p>
                    @if (this.authManager.CurrentUser != null && this.authManager.CurrentUser.Role == Role.Admin)
                    {
                        <a class="btn btn-danger pull-left" asp-controller="Posts" asp-action="Delete" asp-route-id="@post.Id">Delete post</a>
                    }
                </div>
                <div class="media-body container-fluid">
                    <h4 class="media-heading">@post.Title</h4>
                    <p>@post.Description</p>
                </div>
                <br />
                <br />
                <div class="panel">
                    <div class="panel-body">
                        <form asp-controller="Comments" asp-action="Create" asp-route-postId="@this.Model.PostId" method="post">
                            <div class="form-group">
                                <textarea asp-for="@this.Model.Content" class="form-control" rows="5" placeholder="Write your comment here"></textarea>
                                <span asp-validation-for="@this.Model.Content" class="text-danger"></span>
                                <br />
                                <button type="submit" class="btn btn-info">Create comment </button>
                                <a asp-controller="Home" asp-action="Index" class="btn btn-outline-warning">Go back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FMS.MVC/Views/Comments/Delete.cshtml
@model Comment
@inject IAuthManager authManager

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h2>
                You are about to delete this comment. Are you sure?
            </h2>
        </div>
        <br />
        <div class="container-fluid col-2">
            <div class="container-fluid">
                <div class="media-body">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="form-group">
                                <form asp-controller="Comments" asp-action="Delete" asp-route-commentId="@this.Model.Id" method="post">
                                    <input type="submit" value="Yes" class="btn btn-danger">
                                    <a asp-controller="Home" asp-action="Index" class="btn btn-success">No</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FMS.MVC/Views/Comments/Details.cshtml
@model CommentResponseDTO
@inject IUsersService usersService
@inject IAuthManager authManager

@{
    var user = this.usersService.GetByUsername(this.Model.Author);
    var comment = this.Model;

    var currentUser = this.authManager.CurrentUser;

    var userIsLoggedIn = currentUser != null;
    var isAdmin = false;
    if (userIsLoggedIn)
    {
        isAdmin = currentUser.Role == Role.Admin;
    }
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h4>
                Comment by <a asp-controller="Users" asp-action="Details" asp-route-userId="@user.Id">@user.Username</a>
                commented on post <a asp-controller="Posts" asp-action="Details">@comment.PostTitle.</a>
            </h4>
        </div>
        <div class="panel-body">
            <div class="media pull-left">
                <div class="pull-left">
                    <a href="#">
                        <img class="media-object img-circle img-comments" src="~/assets/img/user.gif" />
                    </a>
                    <p class="text-default d-inline pull-left"><a>@comment.Author</a></p>
                    <p>@comment.CreatedOn</p>

                </div>
            </div>
            <div class="container-fluid">
                <div class="media-body">
                    <p>@comment.Content</p>

                    @if (userIsLoggedIn)
                    {
                        @if (currentUser.Role == Role.Admin)
                        {
                            <a asp-controller="Comments" asp-action="Delete" asp-route-commentId="@comment.Id" class=" btn btn-danger">Delete</a>
                        }
                        else if (currentUser.Id == user.Id)
                        {
                            <a asp-controller="Comments" asp-action="Edit" asp-route-commentId="@comment.Id" class="btn btn-default">Edit</a>
                            <a asp-controller="Comments" asp-action="Delete" asp-route-commentId="@comment.Id" class="btn btn-danger">Delete</a>
                            <a asp-controller="Home" asp-action="Index">Back to home</a>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>

FMS.MVC/Views/Comments/Edit.cshtml
@model CommentInputDTO
@inject IAuthManager authManager

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h2>
                Update your comment
            </h2>
        </div>
        <br />
        <div class="container-fluid col-2">
            <div class="container-fluid">
                <div class="media-body">
                    <div class="panel">
                        <div class="panel-body">
                            <form asp-controller="Comments" asp-action="Edit" asp-route-commentId="@this.Model.CommentId" method="post">
                                <div class="form-group">
                                    <textarea asp-for="@this.Model.Content" class="form-control" rows="5">@this.Model.Content</textarea>
                                    <span asp-validation-for="@this.Model.Content" class="text-danger"></span>
                                    <br />
                                    <button type="submit" class="btn btn-info">Save</button>
                                    <a asp-controller="Home" asp-action="Index" class="btn btn-outline-warning">Go back</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>