FMS.MVC/Models/Replies/AllRepliesByCommentViewModel.cs
using FMS.Services.DTOs;
using System.Collections;
using System.Collections.Generic;

namespace FMS.MVC.Models.Replies
{
    public class AllRepliesByCommentViewModel
    {
        public int CommentId { get; set; }
        public List<ReplyResponseDTO> Replies { get; set; } = new List<ReplyResponseDTO>();

    }
}

FMS.MVC/Controllers/RepliesController.cs
using FMS.Data.Utilities.Exceptions;
using FMS.MVC.Models.Replies;
using FMS.Services.DTOs;
using FMS.Services.Mappers;
using FMS.Services.Services.Contracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace FMS.MVC.Controllers
{
    public class RepliesController : Controller
    {
        private readonly ICommentsService commentsService;
        private readonly IRepliesService repliesService;
        private readonly IAuthManager authManager;

        public RepliesController(
            IRepliesService repliesService, 
            IAuthManager authManager, 
            ICommentsService commentsService)
        {
            this.authManager = authManager;
            this.repliesService = repliesService;
            this.commentsService = commentsService;
        }
        // GET: RepliesController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult All(int commentId)
        {
            var model = new AllRepliesByCommentViewModel();

            var replieDTOs = this.repliesService
                .GetAllByCommentId(commentId)
                .Select(c => c.MapToReplyResponse())
                .ToList();

            foreach (var replyDTO in replieDTOs)
            {
                model.Replies.Add(replyDTO);
            }

            model.CommentId = commentId;

            return View(model);
        }

        // GET: RepliesController/Details/5
        public ActionResult Details(ReplyResponseDTO response)
        {
            return View(response);
        }

        [HttpGet]
        // GET: RepliesController/Create
        public ActionResult Create(int commentId)
        {
            var model = new ReplyInputDTO 
            { 
                CommentId = commentId, 
                PostId = this.commentsService.GetById(commentId).PostId
            };

            return View(model);
        }

        // POST: RepliesController/Create
        [HttpPost]
        public ActionResult Create(int commentId, ReplyInputDTO model)
        {
            model.CommentId = commentId;

            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var comment = this.commentsService.GetById(model.CommentId);
                var user = this.authManager.CurrentUser;
                var createdReply = this.repliesService.Create(model.MapToReplyModel(user, comment));
                var response = createdReply.MapToReplyResponse();
                return View("Details", response);
            }
            catch (ApplicationException)
            {
                return this.RedirectToAction(actionName: "Index", controllerName: "Home");
            }
            catch (Exception)
            {
                return this.Redirect("/Error");
            }
        }

        [HttpGet]
        // GET: RepliesController/Edit/5
        public ActionResult Edit(int replyId)
        {
            var currentContent = this.repliesService.GetById(replyId).Content;
            var model = new ReplyInputDTO { ReplyId = replyId, Content = currentContent };
            return View(model);
        }

        // POST: RepliesController/Edit/5
        [HttpPost]
        public ActionResult Edit(int replyId, ReplyInputDTO model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            try
            {
                this.repliesService.Update(replyId, model.Content);
                return this.RedirectToAction(actionName: "Index", controllerName: "Home");
            }
            catch (ApplicationException)
            {
                return this.RedirectToAction(actionName: "Index", controllerName: "Home");
            }
            catch (Exception)
            {
                return this.Redirect("/Error");
            }
        }

        [HttpGet]
        // GET: RepliesController/Delete/5
        public ActionResult Delete(int replyId)
        {
            var model = this.repliesService.GetById(replyId);
            return View(model);
        }

        // POST: RepliesController/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int replyId)
        {
            try
            {
                this.repliesService.Delete(this.repliesService.GetById(replyId));
                return this.RedirectToAction(actionName: "Index", controllerName: "Home");
            }
            catch (ApplicationException)
            {
                return this.RedirectToAction(actionName: "Index", controllerName: "Home");
            }
            catch (Exception)
            {
                return this.Redirect("/Error");
            }
        }
    }
}

FMS.MVC/Views/Replies/All.cshtml
@model AllRepliesByCommentViewModel
@inject ICommentsService commentsService
@inject IPostsService postsService
@inject IUsersService usersService
@inject IAuthManager authManager

@{
    var comment = this.commentsService.GetById(this.Model.CommentId);
    var post = this.postsService.GetById(comment.PostId);
    var user = this.usersService.GetById(post.UserId);

    var currentUser = this.authManager.CurrentUser;

    var userIsLoggedIn = currentUser != null;
    var isAdmin = false;
    if (userIsLoggedIn)
    {
        isAdmin = currentUser.Role == Role.Admin;
    }
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h4>
                All replies to comment by <a asp-controller="Users" asp-action="Details" asp-route-userId="@user.Id">@user.Username</a>
                commented on post <a asp-controller="Posts" asp-action="Details" asp-route-postId="@post.Id">@post.Title</a>
            </h4>
        </div>
        <div class="panel-body">
            <ul class="media-list">
                @foreach (var reply in this.Model.Replies)
                {
                    <li class="media">
                        <div class="pull-left">
                            <a href="#">
                                <img class="media-object img-circle img-comments" src="~/assets/img/user.gif" />
                            </a>
                            <p class="text-default d-inline pull-left"><a>@reply.Author</a></p>
                            <p>@reply.CreatedOn</p>

                        </div>

                        <div class="media-body">
                            <p>@reply.Content</p>

                            @if (userIsLoggedIn)
                            {
                                @if (currentUser.Role == Role.Admin)
                                {
                                    <a asp-controller="Replies" asp-action="Delete" asp-route-replyId="@reply.Id" class=" btn btn-danger">Delete</a>
                                }
                                else if (currentUser.Id == comment.UserId)
                                {
                                    <a asp-controller="Replies" asp-action="Edit" asp-route-replyId="@reply.Id" class="btn btn-default">Edit</a>
                                    <a asp-controller="Replies" asp-action="Delete" asp-route-replyId="@reply.Id" class="btn btn-danger">Delete</a>
                                }
                            }
                        </div>
                    </li>
                }
            </ul>

        </div>
    </div>
</div>

FMS.MVC/Views/Replies/Create.cshtml
@model ReplyInputDTO
@inject IPostsService posetsService
@inject ICommentsService commentsService
@inject IAuthManager authManager

@{
    var post = this.posetsService.GetById(this.Model.PostId);

    var comment = this.commentsService.GetById(this.Model.CommentId);

    var currentUser = this.authManager.CurrentUser;
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h2>
                You are writing a reply for the comment left by
                <a asp-controller="Users" asp-action="Details" asp-route-userId="@post.UserId">@currentUser.Username</a>
                for post
                <a asp-controller="Posts" asp-action="Details" asp-route-postId="@this.Model.PostId">@post.Title</a>
            </h2>
        </div>
        <div class="panel-body">
            <div class="media pull-left">
                <div class="pull-left">
                    <a href="#">
                        <img class="media-object img-circle img-comments" src="~/assets/img/user.gif" />
                    </a>
                    <p class="text-info d-inline pull-right"><a>User details</a></p>
                    <p>@comment.CreatedOn.ToShortDateString()</p>
                    @if (currentUser != null && currentUser.Role == Role.Admin)
                    {
                        <a class="btn btn-danger pull-left" href="google.com">Delete post</a>
                    }
                </div>
            </div>
            <div class="media-body container-fluid">
                <h4 class="media-heading"><a asp-controller="Posts" asp-action="Details" asp-route-postId="@post.Id">@post.Title</a></h4>
                <p>@comment.Content</p>
            </div>

            <br />
            <br />
            <div class="panel">
                <div class="panel-body">
                    <form asp-controller="Replies" asp-action="Create" asp-route-commentId="@this.Model.CommentId" method="post">
                        <div class="form-group">
                            <textarea asp-for="@this.Model.Content" class="form-control" rows="5" placeholder="Write your reply here"></textarea>
                            <span asp-validation-for="@this.Model.Content" class="text-danger"></span>
                            <br />
                            <button type="submit" class="btn btn-info">Save</button>
                            <a asp-controller="Home" asp-action="Index" class="btn btn-outline-warning">Go back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>

</div>

FMS.MVC/Views/Replies/Delete.cshtml
@model Reply
@inject IAuthManager authManager

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h2>
                You are about to delete this reply. Are you sure?
            </h2>
        </div>
        <br />
        <div class="container-fluid col-2">
            <div class="container-fluid">
                <div class="media-body">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="form-group">
                                <form asp-controller="Replies" asp-action="Delete" asp-route-replyId="@this.Model.Id" method="post">
                                    <input type="submit" value="Yes" class="btn btn-danger">
                                    <a asp-controller="Home" asp-action="Index" class="btn btn-success">No</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FMS.MVC/Views/Replies/Details.cshtml
@model ReplyResponseDTO
@inject IUsersService usersService
@inject IAuthManager authManager

@{
    var user = this.usersService.GetByUsername(this.Model.Author);
    var reply = this.Model;

    var currentUser = this.authManager.CurrentUser;

    var userIsLoggedIn = currentUser != null;
    var isAdmin = false;
    if (userIsLoggedIn)
    {
        isAdmin = currentUser.Role == Role.Admin;
    }
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h4>
                Reply by <a asp-controller="Users" asp-action="Details" asp-route-userId="@user.Id">@user.Username</a>
                for post <a asp-controller="Posts" asp-action="Details">@reply.PostTitle.</a>
            </h4>
        </div>

        <div class="panel-body">
            <div class="media pull-left">
                <div class="pull-left">
                    <a href="#">
                        <img class="media-object img-circle img-comments" src="~/assets/img/user.gif" />
                    </a>
                    <p class="text-default d-inline pull-left"><a>@reply.Author</a></p>
                    <p>@reply.CreatedOn</p>

                </div>
            </div>
            <div class="container-fluid">
                <div class="media-body">
                    <p>@reply.Content</p>

                    @if (userIsLoggedIn)
                    {
                        @if (currentUser.Role == Role.Admin)
                        {
                            <a asp-controller="Replies" asp-action="Delete" asp-route-replyId="@reply.Id" class=" btn btn-danger">Delete</a>
                        }
                        else if (currentUser.Id == user.Id)
                        {
                            <a asp-controller="Replies" asp-action="Edit" asp-route-replyId="@reply.Id" class="btn btn-default">Edit</a>
                            <a asp-controller="Replies" asp-action="Delete" asp-route-replyId="@reply.Id" class="btn btn-danger">Delete</a>
                            <a asp-controller="Home" asp-action="Index">Back to home</a>
                        }
                    }
                </div>
            </div>

        </div>
    </div>

</div>

FMS.MVC/Views/Replies/Edit.cshtml
@model ReplyInputDTO
@inject IAuthManager authManager

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h2>
                Update your reply
            </h2>
        </div>
        <br />
        <div class="container-fluid col-2">
            <div class="container-fluid">
                <div class="media-body">
                    <div class="panel">
                        <div class="panel-body">
                            <form asp-controller="Replies" asp-action="Edit" asp-route-replyId="@this.Model.ReplyId" method="post">
                                <div class="form-group">
                                    <textarea asp-for="@this.Model.Content" class="form-control" rows="5">@this.Model.Content</textarea>
                                    <span asp-validation-for="@this.Model.Content" class="text-danger"></span>
                                    <br />
                                    <button type="submit" class="btn btn-info">Save</button>
                                    <a asp-controller="Home" asp-action="Index" class="btn btn-outline-warning">Go back</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>